export const CURRENT_ADMIN_ID = "00000000-0000-0000-0000-000000000001";
export const CURRENT_BOOTSTRAP_USER_ID = "00000000-0000-0000-0000-000000000101";
export const CURRENT_BOOTSTRAP_USER_NAME = "کاربر دمو";

// UI-side mirror of the current database shape for part_kinds until the API is wired.
export const PART_KINDS_CATALOG = [
  {
    id: "pk-system-1",
    admin_id: null,
    part_kind_id: 1,
    part_kind_code: "unit",
    org_part_kind_title: "یونیت",
    code: "unit",
    title: "یونیت",
    sort_order: 1,
    is_system: true,
  },
  {
    id: "pk-system-2",
    admin_id: null,
    part_kind_id: 2,
    part_kind_code: "stretcher",
    org_part_kind_title: "ترک",
    code: "stretcher",
    title: "ترک",
    sort_order: 2,
    is_system: true,
  },
  {
    id: "pk-system-3",
    admin_id: null,
    part_kind_id: 3,
    part_kind_code: "shelf",
    org_part_kind_title: "طبقه",
    code: "shelf",
    title: "طبقه",
    sort_order: 3,
    is_system: true,
  },
  {
    id: "pk-system-4",
    admin_id: null,
    part_kind_id: 4,
    part_kind_code: "drawer",
    org_part_kind_title: "کشو",
    code: "drawer",
    title: "کشو",
    sort_order: 4,
    is_system: true,
  },
  {
    id: "pk-system-5",
    admin_id: null,
    part_kind_id: 5,
    part_kind_code: "partition",
    org_part_kind_title: "جداکننده",
    code: "partition",
    title: "جداکننده",
    sort_order: 5,
    is_system: true,
  },
  {
    id: "pk-system-6",
    admin_id: null,
    part_kind_id: 6,
    part_kind_code: "door",
    org_part_kind_title: "درب",
    code: "door",
    title: "درب",
    sort_order: 6,
    is_system: true,
  },
  {
    id: "pk-system-7",
    admin_id: null,
    part_kind_id: 7,
    part_kind_code: "face_panel",
    org_part_kind_title: "پنل نما",
    code: "face_panel",
    title: "پنل نما",
    sort_order: 7,
    is_system: true,
  },
  {
    id: "pk-system-8",
    admin_id: null,
    part_kind_id: 8,
    part_kind_code: "toe_kick",
    org_part_kind_title: "پاخور",
    code: "toe_kick",
    title: "پاخور",
    sort_order: 8,
    is_system: true,
  },
  {
    id: "pk-system-9",
    admin_id: null,
    part_kind_id: 9,
    part_kind_code: "frame",
    org_part_kind_title: "فریم",
    code: "frame",
    title: "فریم",
    sort_order: 9,
    is_system: true,
  },
];
